### PR TITLE
Gem jar divya

### PR DESCRIPTION
**Pull request by gem-divyamadan**
I have added the updated code.

### CODE REVIEW

**Review by Gem-NeerajSingh — COMMENTED** [review]
Static waits must be replaced with dynamic waits.

**Comment by gem-divyamadan** [comment]
I have updated the code as suggested.

**Comment by gem-divyamadan** [comment]
I have updated the code as suggested.

**Comment by gem-divyamadan** [comment]
> Static waits must be replaced with dynamic waits.
This is done.

**Review by Gem-NeerajSingh — COMMENTED** [review]
Conflict in below file
src/main/java/com/qa/MIS/StepDefinition/StepDefinition.java

**Review by Gem-NeerajSingh — APPROVED** [review]

**Pull request merged**
